//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMSWebApi.App_Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Added Successfully.
        /// </summary>
        public static string AccessoryAdded {
            get {
                return ResourceManager.GetString("AccessoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Deleted Successfully.
        /// </summary>
        public static string AccessoryDeleted {
            get {
                return ResourceManager.GetString("AccessoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Updated Successfully.
        /// </summary>
        public static string AccessoryUpdated {
            get {
                return ResourceManager.GetString("AccessoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent details added Successfully.
        /// </summary>
        public static string AgentAdded {
            get {
                return ResourceManager.GetString("AgentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Deleted Successfully.
        /// </summary>
        public static string AgentDeleted {
            get {
                return ResourceManager.GetString("AgentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent details updated Successfully.
        /// </summary>
        public static string AgentUpdated {
            get {
                return ResourceManager.GetString("AgentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Added Successfully.
        /// </summary>
        public static string CollectionAdded {
            get {
                return ResourceManager.GetString("CollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Deleted Successfully.
        /// </summary>
        public static string CollectionDeleted {
            get {
                return ResourceManager.GetString("CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Updated Successfully.
        /// </summary>
        public static string CollectionUpdated {
            get {
                return ResourceManager.GetString("CollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information Added Successfully.
        /// </summary>
        public static string CompanyInfoAdded {
            get {
                return ResourceManager.GetString("CompanyInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information Updated Successfully.
        /// </summary>
        public static string CompanyInfoUpdated {
            get {
                return ResourceManager.GetString("CompanyInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Details Added Successfully.
        /// </summary>
        public static string CourierAdded {
            get {
                return ResourceManager.GetString("CourierAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Deleted Successfully.
        /// </summary>
        public static string CourierDeleted {
            get {
                return ResourceManager.GetString("CourierDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Details Updated Successfully.
        /// </summary>
        public static string CourierUpdated {
            get {
                return ResourceManager.GetString("CourierUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Added Successfully.
        /// </summary>
        public static string CustomerAdded {
            get {
                return ResourceManager.GetString("CustomerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Deleted Successfully.
        /// </summary>
        public static string CustomerDeleted {
            get {
                return ResourceManager.GetString("CustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Customer has associated Sales Order.So can&apos;t be deleted..
        /// </summary>
        public static string CustomerNotDeleted {
            get {
                return ResourceManager.GetString("CustomerNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Updated Successfully.
        /// </summary>
        public static string CustomerUpdated {
            get {
                return ResourceManager.GetString("CustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year Added Successfully.
        /// </summary>
        public static string FinancialYearAdded {
            get {
                return ResourceManager.GetString("FinancialYearAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year Deleted Successfully.
        /// </summary>
        public static string FinancialYearDeleted {
            get {
                return ResourceManager.GetString("FinancialYearDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year Updated Successfully.
        /// </summary>
        public static string FinancialYearUpdated {
            get {
                return ResourceManager.GetString("FinancialYearUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Added Successfully.
        /// </summary>
        public static string FomDensityAdded {
            get {
                return ResourceManager.GetString("FomDensityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Deleted Successfully.
        /// </summary>
        public static string FomDensityDeleted {
            get {
                return ResourceManager.GetString("FomDensityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Updated Successfully.
        /// </summary>
        public static string FomDensityUpdated {
            get {
                return ResourceManager.GetString("FomDensityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Added Successfully.
        /// </summary>
        public static string FomSizeAdded {
            get {
                return ResourceManager.GetString("FomSizeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Deleted Successfully.
        /// </summary>
        public static string FomSizeDeleted {
            get {
                return ResourceManager.GetString("FomSizeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Updated Successfully.
        /// </summary>
        public static string FomSizeUpdated {
            get {
                return ResourceManager.GetString("FomSizeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Added Successfully.
        /// </summary>
        public static string FomSuggestedMMAdded {
            get {
                return ResourceManager.GetString("FomSuggestedMMAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Deleted Successfully.
        /// </summary>
        public static string FomSuggestedMMDeleted {
            get {
                return ResourceManager.GetString("FomSuggestedMMDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Updated Successfully.
        /// </summary>
        public static string FomSuggestedMMUpdated {
            get {
                return ResourceManager.GetString("FomSuggestedMMUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Added Successfully.
        /// </summary>
        public static string FWRDesignAdded {
            get {
                return ResourceManager.GetString("FWRDesignAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Deleted Successfully.
        /// </summary>
        public static string FWRDesignDeleted {
            get {
                return ResourceManager.GetString("FWRDesignDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Updated Successfully.
        /// </summary>
        public static string FWRDesignUpdated {
            get {
                return ResourceManager.GetString("FWRDesignUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Cancel, as some items already delivered.
        /// </summary>
        public static string GINExists {
            get {
                return ResourceManager.GetString("GINExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter issued quantity for atleast one item.
        /// </summary>
        public static string GINnotUpdated {
            get {
                return ResourceManager.GetString("GINnotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRN Added Successfully.
        /// </summary>
        public static string GRNAdded {
            get {
                return ResourceManager.GetString("GRNAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Added Successfully.
        /// </summary>
        public static string HsnAdded {
            get {
                return ResourceManager.GetString("HsnAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Deleted Successfully.
        /// </summary>
        public static string HsnDeleted {
            get {
                return ResourceManager.GetString("HsnDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Updated Successfully.
        /// </summary>
        public static string HsnUpdated {
            get {
                return ResourceManager.GetString("HsnUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice is Created for this GIN.
        /// </summary>
        public static string InvoiceCreated {
            get {
                return ResourceManager.GetString("InvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Added Successfully.
        /// </summary>
        public static string MatSizeAdded {
            get {
                return ResourceManager.GetString("MatSizeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Deleted Successfully.
        /// </summary>
        public static string MatSizeDeleted {
            get {
                return ResourceManager.GetString("MatSizeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Updated Successfully.
        /// </summary>
        public static string MatSizeUpdated {
            get {
                return ResourceManager.GetString("MatSizeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Added Successfully.
        /// </summary>
        public static string MatThicknessAdded {
            get {
                return ResourceManager.GetString("MatThicknessAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Deleted Successfully.
        /// </summary>
        public static string MatThicknessDeleted {
            get {
                return ResourceManager.GetString("MatThicknessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Updated Successfully.
        /// </summary>
        public static string MatThicknessUpdated {
            get {
                return ResourceManager.GetString("MatThicknessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Created Successfully.
        /// </summary>
        public static string MQCreated {
            get {
                return ResourceManager.GetString("MQCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Quotation Updated Successfully.
        /// </summary>
        public static string MQUpdated {
            get {
                return ResourceManager.GetString("MQUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Selection Added Successfully.
        /// </summary>
        public static string MSAdded {
            get {
                return ResourceManager.GetString("MSAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Selection Updated Successfully.
        /// </summary>
        public static string MSUpdated {
            get {
                return ResourceManager.GetString("MSUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password didn&apos;t Matched.
        /// </summary>
        public static string OldPasswordMismatched {
            get {
                return ResourceManager.GetString("OldPasswordMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id does not exist..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is De-Active. Password cannot be reset..
        /// </summary>
        public static string PasswordResetForDeActiveUser {
            get {
                return ResourceManager.GetString("PasswordResetForDeActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated Successfully.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Generated Successfully.
        /// </summary>
        public static string POAdded {
            get {
                return ResourceManager.GetString("POAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order is Approved.
        /// </summary>
        public static string POApproved {
            get {
                return ResourceManager.GetString("POApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order is Cancelled Successfully.
        /// </summary>
        public static string POCancelled {
            get {
                return ResourceManager.GetString("POCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order can&apos;t be Cancelled.
        /// </summary>
        public static string PONotCancelled {
            get {
                return ResourceManager.GetString("PONotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Updated Successfully.
        /// </summary>
        public static string POUpdated {
            get {
                return ResourceManager.GetString("POUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Added Successfully.
        /// </summary>
        public static string QualityAdded {
            get {
                return ResourceManager.GetString("QualityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Deleted Successfully.
        /// </summary>
        public static string QualityDeleted {
            get {
                return ResourceManager.GetString("QualityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Updated Successfully.
        /// </summary>
        public static string QualityUpdated {
            get {
                return ResourceManager.GetString("QualityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Added Successfully.
        /// </summary>
        public static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already assigned to other user. cannot be deleted.
        /// </summary>
        public static string RoleCannotBeDeleted {
            get {
                return ResourceManager.GetString("RoleCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Deleted Successfully.
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Updated Successfully.
        /// </summary>
        public static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice is Approved Successfully..
        /// </summary>
        public static string SalesInvoiceApproved {
            get {
                return ResourceManager.GetString("SalesInvoiceApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice Updated Successfully.
        /// </summary>
        public static string SalesInvoiceUpdated {
            get {
                return ResourceManager.GetString("SalesInvoiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Added Successfully.
        /// </summary>
        public static string ShadeAdded {
            get {
                return ResourceManager.GetString("ShadeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Deleted Successfully.
        /// </summary>
        public static string ShadeDeleted {
            get {
                return ResourceManager.GetString("ShadeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Updated Successfully.
        /// </summary>
        public static string ShadeUpdated {
            get {
                return ResourceManager.GetString("ShadeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order Generated Successfully.
        /// </summary>
        public static string SOAdded {
            get {
                return ResourceManager.GetString("SOAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order Approved Successfully.
        /// </summary>
        public static string SOApproved {
            get {
                return ResourceManager.GetString("SOApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Cancel, as it is already Approved By Admin.
        /// </summary>
        public static string SOApprovedByAdmin {
            get {
                return ResourceManager.GetString("SOApprovedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Cancelled Successfully.
        /// </summary>
        public static string SOCancelled {
            get {
                return ResourceManager.GetString("SOCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Status changed to Completed Forcefully.
        /// </summary>
        public static string SOForcefullyComplete {
            get {
                return ResourceManager.GetString("SOForcefullyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Order Generated Successfully.
        /// </summary>
        public static string SOUpdated {
            get {
                return ResourceManager.GetString("SOUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Added Successfully.
        /// </summary>
        public static string SupplierAdded {
            get {
                return ResourceManager.GetString("SupplierAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Deleted Successfully.
        /// </summary>
        public static string SupplierDeleted {
            get {
                return ResourceManager.GetString("SupplierDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Updated Successfully.
        /// </summary>
        public static string SupplierUpdated {
            get {
                return ResourceManager.GetString("SupplierUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is Added in Stock.
        /// </summary>
        public static string TrnProductStockAdded {
            get {
                return ResourceManager.GetString("TrnProductStockAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock is Updated Successfully.
        /// </summary>
        public static string TrnProductStockUpdated {
            get {
                return ResourceManager.GetString("TrnProductStockUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Activated Successfully.
        /// </summary>
        public static string UserActivate {
            get {
                return ResourceManager.GetString("UserActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added Successfully.
        /// </summary>
        public static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UserCredentialsInvalid {
            get {
                return ResourceManager.GetString("UserCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is De-Activated Successfully.
        /// </summary>
        public static string UserDeActivate {
            get {
                return ResourceManager.GetString("UserDeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User is inactive. Please contact Administrator..
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does not exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details Updated Successfully.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
    }
}
