//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMSWebApi.App_Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Added Successfully.
        /// </summary>
        public static string CollectionAdded {
            get {
                return ResourceManager.GetString("CollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Deleted Successfully.
        /// </summary>
        public static string CollectionDeleted {
            get {
                return ResourceManager.GetString("CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Updated Successfully.
        /// </summary>
        public static string CollectionUpdated {
            get {
                return ResourceManager.GetString("CollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information Added Successfully.
        /// </summary>
        public static string CompanyInfoAdded {
            get {
                return ResourceManager.GetString("CompanyInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information Updated Successfully.
        /// </summary>
        public static string CompanyInfoUpdated {
            get {
                return ResourceManager.GetString("CompanyInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Added Successfully.
        /// </summary>
        public static string CustomerAdded {
            get {
                return ResourceManager.GetString("CustomerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Deleted Successfully.
        /// </summary>
        public static string CustomerDeleted {
            get {
                return ResourceManager.GetString("CustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Updated Successfully.
        /// </summary>
        public static string CustomerUpdated {
            get {
                return ResourceManager.GetString("CustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Added Successfully.
        /// </summary>
        public static string FomDensityAdded {
            get {
                return ResourceManager.GetString("FomDensityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Deleted Successfully.
        /// </summary>
        public static string FomDensityDeleted {
            get {
                return ResourceManager.GetString("FomDensityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Density Updated Successfully.
        /// </summary>
        public static string FomDensityUpdated {
            get {
                return ResourceManager.GetString("FomDensityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Added Successfully.
        /// </summary>
        public static string FomSizeAdded {
            get {
                return ResourceManager.GetString("FomSizeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Deleted Successfully.
        /// </summary>
        public static string FomSizeDeleted {
            get {
                return ResourceManager.GetString("FomSizeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Size Updated Successfully.
        /// </summary>
        public static string FomSizeUpdated {
            get {
                return ResourceManager.GetString("FomSizeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Added Successfully.
        /// </summary>
        public static string FomSuggestedMMAdded {
            get {
                return ResourceManager.GetString("FomSuggestedMMAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Deleted Successfully.
        /// </summary>
        public static string FomSuggestedMMDeleted {
            get {
                return ResourceManager.GetString("FomSuggestedMMDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foam Suggested MM Updated Successfully.
        /// </summary>
        public static string FomSuggestedMMUpdated {
            get {
                return ResourceManager.GetString("FomSuggestedMMUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Added Successfully.
        /// </summary>
        public static string FWRDesignAdded {
            get {
                return ResourceManager.GetString("FWRDesignAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Deleted Successfully.
        /// </summary>
        public static string FWRDesignDeleted {
            get {
                return ResourceManager.GetString("FWRDesignDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWR Design Updated Successfully.
        /// </summary>
        public static string FWRDesignUpdated {
            get {
                return ResourceManager.GetString("FWRDesignUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Added Successfully.
        /// </summary>
        public static string HsnAdded {
            get {
                return ResourceManager.GetString("HsnAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Deleted Successfully.
        /// </summary>
        public static string HsnDeleted {
            get {
                return ResourceManager.GetString("HsnDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hsn Updated Successfully.
        /// </summary>
        public static string HsnUpdated {
            get {
                return ResourceManager.GetString("HsnUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Added Successfully.
        /// </summary>
        public static string MatSizeAdded {
            get {
                return ResourceManager.GetString("MatSizeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Deleted Successfully.
        /// </summary>
        public static string MatSizeDeleted {
            get {
                return ResourceManager.GetString("MatSizeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Size Updated Successfully.
        /// </summary>
        public static string MatSizeUpdated {
            get {
                return ResourceManager.GetString("MatSizeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Added Successfully.
        /// </summary>
        public static string MatThicknessAdded {
            get {
                return ResourceManager.GetString("MatThicknessAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Deleted Successfully.
        /// </summary>
        public static string MatThicknessDeleted {
            get {
                return ResourceManager.GetString("MatThicknessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat Thickness Updated Successfully.
        /// </summary>
        public static string MatThicknessUpdated {
            get {
                return ResourceManager.GetString("MatThicknessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password didn&apos;t Matched.
        /// </summary>
        public static string OldPasswordMismatched {
            get {
                return ResourceManager.GetString("OldPasswordMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id does not exist..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated Successfully.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Added Successfully.
        /// </summary>
        public static string QualityAdded {
            get {
                return ResourceManager.GetString("QualityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Deleted Successfully.
        /// </summary>
        public static string QualityDeleted {
            get {
                return ResourceManager.GetString("QualityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Updated Successfully.
        /// </summary>
        public static string QualityUpdated {
            get {
                return ResourceManager.GetString("QualityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Added Successfully.
        /// </summary>
        public static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already assigned to other user. cannot be deleted.
        /// </summary>
        public static string RoleCannotBeDeleted {
            get {
                return ResourceManager.GetString("RoleCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Deleted Successfully.
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Updated Successfully.
        /// </summary>
        public static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Added Successfully.
        /// </summary>
        public static string ShadeAdded {
            get {
                return ResourceManager.GetString("ShadeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Deleted Successfully.
        /// </summary>
        public static string ShadeDeleted {
            get {
                return ResourceManager.GetString("ShadeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade Updated Successfully.
        /// </summary>
        public static string ShadeUpdated {
            get {
                return ResourceManager.GetString("ShadeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Added Successfully.
        /// </summary>
        public static string SupplierAdded {
            get {
                return ResourceManager.GetString("SupplierAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Deleted Successfully.
        /// </summary>
        public static string SupplierDeleted {
            get {
                return ResourceManager.GetString("SupplierDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Updated Successfully.
        /// </summary>
        public static string SupplierUpdated {
            get {
                return ResourceManager.GetString("SupplierUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is Added in Stock.
        /// </summary>
        public static string TrnProductStockAdded {
            get {
                return ResourceManager.GetString("TrnProductStockAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock is Updated Successfully.
        /// </summary>
        public static string TrnProductStockUpdated {
            get {
                return ResourceManager.GetString("TrnProductStockUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added Successfully.
        /// </summary>
        public static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UserCredentialsInvalid {
            get {
                return ResourceManager.GetString("UserCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User is inactive. Please contact Administrator..
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does not exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details Updated Successfully.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
    }
}
