//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstAgent
    {
        public MstAgent()
        {
            this.TrnMaterialQuotations = new HashSet<TrnMaterialQuotation>();
            this.TrnMaterialSelections = new HashSet<TrnMaterialSelection>();
            this.TrnSaleOrders = new HashSet<TrnSaleOrder>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pin { get; set; }
        public int commision { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual ICollection<TrnMaterialQuotation> TrnMaterialQuotations { get; set; }
        public virtual ICollection<TrnMaterialSelection> TrnMaterialSelections { get; set; }
        public virtual ICollection<TrnSaleOrder> TrnSaleOrders { get; set; }
    }
}
