//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCollection
    {
        public MstCollection()
        {
            this.MstDesigns = new HashSet<MstDesign>();
            this.MstQualities = new HashSet<MstQuality>();
            this.MstShades = new HashSet<MstShade>();
        }
    
        public long id { get; set; }
        public long categoryId { get; set; }
        public long supplierId { get; set; }
        public string collectionCode { get; set; }
        public string collectionName { get; set; }
        public string description { get; set; }
        public string manufacturerName { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual MstCategory MstCategory { get; set; }
        public virtual MstSupplier MstSupplier { get; set; }
        public virtual ICollection<MstDesign> MstDesigns { get; set; }
        public virtual ICollection<MstQuality> MstQualities { get; set; }
        public virtual ICollection<MstShade> MstShades { get; set; }
    }
}
