//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstFinancialYear
    {
        public long id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string financialYear { get; set; }
        public int poNumber { get; set; }
        public int soNumber { get; set; }
        public int grnNumber { get; set; }
        public int ginNumber { get; set; }
        public int poInvoiceNumber { get; set; }
        public int soInvoiceNumber { get; set; }
        public int materialSelectionNumber { get; set; }
        public int materialQuotationNumber { get; set; }
        public int curtainSelectionNumber { get; set; }
        public int curtainQuotationNumber { get; set; }
        public int jobCardNumber { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public int apNumber { get; set; }
    }
}
