//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstPattern
    {
        public MstPattern()
        {
            this.MstTailorPatternChargeDetails = new HashSet<MstTailorPatternChargeDetail>();
            this.TrnCurtainQuotationItems = new HashSet<TrnCurtainQuotationItem>();
            this.TrnCurtainSelectionItems = new HashSet<TrnCurtainSelectionItem>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public decimal fabricHeight { get; set; }
        public Nullable<decimal> liningHeight { get; set; }
        public Nullable<decimal> woFabricHeight { get; set; }
        public Nullable<decimal> woLiningHeight { get; set; }
        public int meterPerInch { get; set; }
        public int widthPerInch { get; set; }
        public decimal setRateForCustomer { get; set; }
        public Nullable<decimal> verticalPatch { get; set; }
        public Nullable<decimal> horizontalPatch { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual ICollection<MstTailorPatternChargeDetail> MstTailorPatternChargeDetails { get; set; }
        public virtual ICollection<TrnCurtainQuotationItem> TrnCurtainQuotationItems { get; set; }
        public virtual ICollection<TrnCurtainSelectionItem> TrnCurtainSelectionItems { get; set; }
    }
}
