//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUnitOfMeasure
    {
        public MstUnitOfMeasure()
        {
            this.MstCategories = new HashSet<MstCategory>();
            this.MstAccessories = new HashSet<MstAccessory>();
        }
    
        public long id { get; set; }
        public string uomCode { get; set; }
        public string uomName { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual ICollection<MstCategory> MstCategories { get; set; }
        public virtual ICollection<MstAccessory> MstAccessories { get; set; }
    }
}
