//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCurtainSelection
    {
        public TrnCurtainSelection()
        {
            this.TrnCurtainQuotations = new HashSet<TrnCurtainQuotation>();
            this.TrnCurtainSelectionItems = new HashSet<TrnCurtainSelectionItem>();
        }
    
        public long id { get; set; }
        public long customerId { get; set; }
        public Nullable<long> shippingAddressId { get; set; }
        public string curtainSelectionNumber { get; set; }
        public System.DateTime curtainSelectionDate { get; set; }
        public Nullable<long> referById { get; set; }
        public bool isQuotationCreated { get; set; }
        public string financialYear { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual MstAgent MstAgent { get; set; }
        public virtual MstCustomer MstCustomer { get; set; }
        public virtual MstCustomerAddress MstCustomerAddress { get; set; }
        public virtual ICollection<TrnCurtainQuotation> TrnCurtainQuotations { get; set; }
        public virtual ICollection<TrnCurtainSelectionItem> TrnCurtainSelectionItems { get; set; }
    }
}
