//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCurtainQuotation
    {
        public TrnCurtainQuotation()
        {
            this.TrnAdvancePayments = new HashSet<TrnAdvancePayment>();
            this.TrnCurtainQuotationItems = new HashSet<TrnCurtainQuotationItem>();
        }
    
        public long id { get; set; }
        public long curtainSelectionId { get; set; }
        public string curtainQuotationNumber { get; set; }
        public System.DateTime curtainQuotationDate { get; set; }
        public long customerId { get; set; }
        public Nullable<long> referById { get; set; }
        public long totalAmount { get; set; }
        public string financialYear { get; set; }
        public string status { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual MstAgent MstAgent { get; set; }
        public virtual MstCustomer MstCustomer { get; set; }
        public virtual TrnCurtainSelection TrnCurtainSelection { get; set; }
        public virtual ICollection<TrnAdvancePayment> TrnAdvancePayments { get; set; }
        public virtual ICollection<TrnCurtainQuotationItem> TrnCurtainQuotationItems { get; set; }
    }
}
