//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnPurchaseOrder
    {
        public TrnPurchaseOrder()
        {
            this.TrnGoodReceiveNoteItems = new HashSet<TrnGoodReceiveNoteItem>();
            this.TrnPurchaseOrderItems = new HashSet<TrnPurchaseOrderItem>();
        }
    
        public long id { get; set; }
        public long courierId { get; set; }
        public string courierMode { get; set; }
        public Nullable<long> saleOrderId { get; set; }
        public Nullable<int> saleOrderNumber { get; set; }
        public long supplierId { get; set; }
        public long locationId { get; set; }
        public string orderNumber { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> expectedDeliveryDate { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public string remark { get; set; }
        public string status { get; set; }
        public string financialYear { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual MstCompanyLocation MstCompanyLocation { get; set; }
        public virtual MstCourier MstCourier { get; set; }
        public virtual MstSupplier MstSupplier { get; set; }
        public virtual ICollection<TrnGoodReceiveNoteItem> TrnGoodReceiveNoteItems { get; set; }
        public virtual TrnSaleOrder TrnSaleOrder { get; set; }
        public virtual ICollection<TrnPurchaseOrderItem> TrnPurchaseOrderItems { get; set; }
    }
}
