//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnWorkOrder
    {
        public TrnWorkOrder()
        {
            this.TrnWorkOrderItems = new HashSet<TrnWorkOrderItem>();
        }
    
        public long id { get; set; }
        public long curtainQuotationId { get; set; }
        public string workOrderNumber { get; set; }
        public System.DateTime workOrderDate { get; set; }
        public long customerId { get; set; }
        public Nullable<long> tailorId { get; set; }
        public string financialYear { get; set; }
        public Nullable<System.DateTime> expectedDeliveryDate { get; set; }
        public string status { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
    
        public virtual MstCustomer MstCustomer { get; set; }
        public virtual MstTailor MstTailor { get; set; }
        public virtual TrnCurtainQuotation TrnCurtainQuotation { get; set; }
        public virtual ICollection<TrnWorkOrderItem> TrnWorkOrderItems { get; set; }
    }
}
