//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAccessory
    {
        public string Category { get; set; }
        public string itemCode { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string uom { get; set; }
        public string hsnCode { get; set; }
        public string hsnWithGST { get; set; }
        public string gst { get; set; }
        public decimal sellingRate { get; set; }
        public Nullable<decimal> sellingRateWithGst { get; set; }
        public decimal purchaseRate { get; set; }
        public Nullable<decimal> purchaseRateWithGst { get; set; }
        public Nullable<decimal> availableStock { get; set; }
    }
}
