//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDasBoard
    {
        public Nullable<int> totalOutStandingAmount { get; set; }
        public Nullable<int> totalSalesCount { get; set; }
        public int totalPaymentDue { get; set; }
        public Nullable<int> totalPurchaseCount { get; set; }
        public Nullable<int> ytdSale { get; set; }
        public Nullable<int> currentMonthSale { get; set; }
        public Nullable<int> itemsCountBelowReorderLevel { get; set; }
        public Nullable<int> totalStockValue { get; set; }
    }
}
