//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFoam
    {
        public string Category { get; set; }
        public string Collection { get; set; }
        public string qualityCode { get; set; }
        public string density { get; set; }
        public string sizeCode { get; set; }
        public string itemCode { get; set; }
        public string hsnCode { get; set; }
        public string gst { get; set; }
        public decimal purchaseRatePerMM { get; set; }
        public string purchaseRatePerMMWithGst { get; set; }
        public decimal purchaseRatePerKG { get; set; }
        public string purchaseRatePerKGWithGst { get; set; }
        public decimal sellingRatePerMM { get; set; }
        public string sellingRatePerMMWithGst { get; set; }
        public decimal sellingRatePerKG { get; set; }
        public string sellingRatePerKGWithGst { get; set; }
        public Nullable<decimal> availableStock { get; set; }
    }
}
