//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwitemBelowReOrderLevelList
    {
        public string categoryCode { get; set; }
        public string collectionCode { get; set; }
        public string qualityCode { get; set; }
        public string designCode { get; set; }
        public string shadeCode { get; set; }
        public Nullable<int> serialNumber { get; set; }
        public string itemCode { get; set; }
        public string thicknessCode { get; set; }
        public string sizeCode { get; set; }
    }
}
