//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebAPIdbEntities : DbContext
    {
        public WebAPIdbEntities()
            : base("name=WebAPIdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CFGRoleMenu> CFGRoleMenus { get; set; }
        public virtual DbSet<MstAccessory> MstAccessories { get; set; }
        public virtual DbSet<MstAgent> MstAgents { get; set; }
        public virtual DbSet<MstCategory> MstCategories { get; set; }
        public virtual DbSet<MstCollection> MstCollections { get; set; }
        public virtual DbSet<MstCompanyInfo> MstCompanyInfoes { get; set; }
        public virtual DbSet<MstCompanyLocation> MstCompanyLocations { get; set; }
        public virtual DbSet<MstCourier> MstCouriers { get; set; }
        public virtual DbSet<MstCustomer> MstCustomers { get; set; }
        public virtual DbSet<MstCustomerAddress> MstCustomerAddresses { get; set; }
        public virtual DbSet<MstFinancialYear> MstFinancialYears { get; set; }
        public virtual DbSet<MstFomDensity> MstFomDensities { get; set; }
        public virtual DbSet<MstFomSize> MstFomSizes { get; set; }
        public virtual DbSet<MstFomSuggestedMM> MstFomSuggestedMMs { get; set; }
        public virtual DbSet<MstFWRDesign> MstFWRDesigns { get; set; }
        public virtual DbSet<MstFWRShade> MstFWRShades { get; set; }
        public virtual DbSet<MstHsn> MstHsns { get; set; }
        public virtual DbSet<MstMatSize> MstMatSizes { get; set; }
        public virtual DbSet<MstMatThickness> MstMatThicknesses { get; set; }
        public virtual DbSet<MstMenu> MstMenus { get; set; }
        public virtual DbSet<MstQuality> MstQualities { get; set; }
        public virtual DbSet<MstRole> MstRoles { get; set; }
        public virtual DbSet<MstSupplier> MstSuppliers { get; set; }
        public virtual DbSet<MstSupplierAddress> MstSupplierAddresses { get; set; }
        public virtual DbSet<MstUnitOfMeasure> MstUnitOfMeasures { get; set; }
        public virtual DbSet<MstUser> MstUsers { get; set; }
        public virtual DbSet<MstuserType> MstuserTypes { get; set; }
        public virtual DbSet<TrnMaterialQuotation> TrnMaterialQuotations { get; set; }
        public virtual DbSet<TrnMaterialQuotationItem> TrnMaterialQuotationItems { get; set; }
        public virtual DbSet<TrnMaterialSelection> TrnMaterialSelections { get; set; }
        public virtual DbSet<TrnMaterialSelectionItem> TrnMaterialSelectionItems { get; set; }
        public virtual DbSet<TrnPurchaseOrder> TrnPurchaseOrders { get; set; }
        public virtual DbSet<TrnPurchaseOrderItem> TrnPurchaseOrderItems { get; set; }
        public virtual DbSet<TrnSaleOrderItem> TrnSaleOrderItems { get; set; }
        public virtual DbSet<TrnSalesInvoiceItem> TrnSalesInvoiceItems { get; set; }
        public virtual DbSet<vwDasBoard> vwDasBoards { get; set; }
        public virtual DbSet<vwitemBelowReOrderLevelList> vwitemBelowReOrderLevelLists { get; set; }
        public virtual DbSet<MstTailorPatternChargeDetail> MstTailorPatternChargeDetails { get; set; }
        public virtual DbSet<MstTailor> MstTailors { get; set; }
        public virtual DbSet<TrnAdvancePayment> TrnAdvancePayments { get; set; }
        public virtual DbSet<TrnCurtainSelectionItem> TrnCurtainSelectionItems { get; set; }
        public virtual DbSet<TrnCurtainSelection> TrnCurtainSelections { get; set; }
        public virtual DbSet<MstPattern> MstPatterns { get; set; }
        public virtual DbSet<TrnCurtainQuotation> TrnCurtainQuotations { get; set; }
        public virtual DbSet<TrnCurtainQuotationItem> TrnCurtainQuotationItems { get; set; }
        public virtual DbSet<TrnSalesInvoice> TrnSalesInvoices { get; set; }
        public virtual DbSet<TrnWorkOrderItem> TrnWorkOrderItems { get; set; }
        public virtual DbSet<vwAccessory> vwAccessories { get; set; }
        public virtual DbSet<vwFoam> vwFoams { get; set; }
        public virtual DbSet<vwFWR> vwFWRs { get; set; }
        public virtual DbSet<vwMattress> vwMattresses { get; set; }
        public virtual DbSet<TrnWorkOrder> TrnWorkOrders { get; set; }
        public virtual DbSet<vwLabourJob> vwLabourJobs { get; set; }
        public virtual DbSet<TrnGoodReceiveNote> TrnGoodReceiveNotes { get; set; }
        public virtual DbSet<TrnGoodIssueNoteItem> TrnGoodIssueNoteItems { get; set; }
        public virtual DbSet<TrnGoodIssueNote> TrnGoodIssueNotes { get; set; }
        public virtual DbSet<TrnSaleOrder> TrnSaleOrders { get; set; }
        public virtual DbSet<TrnGoodReceiveNoteItem> TrnGoodReceiveNoteItems { get; set; }
        public virtual DbSet<TrnProductStockDetail> TrnProductStockDetails { get; set; }
        public virtual DbSet<TrnProductStock> TrnProductStocks { get; set; }
    
        public virtual ObjectResult<MstCategory> GET_CATEGORY_ID(string categories)
        {
            var categoriesParameter = categories != null ?
                new ObjectParameter("Categories", categories) :
                new ObjectParameter("Categories", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCategory>("GET_CATEGORY_ID", categoriesParameter);
        }
    
        public virtual ObjectResult<MstCategory> GET_CATEGORY_ID(string categories, MergeOption mergeOption)
        {
            var categoriesParameter = categories != null ?
                new ObjectParameter("Categories", categories) :
                new ObjectParameter("Categories", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCategory>("GET_CATEGORY_ID", mergeOption, categoriesParameter);
        }
    
        public virtual ObjectResult<MstCollection> GET_COLLECTION_ID(string collection)
        {
            var collectionParameter = collection != null ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCollection>("GET_COLLECTION_ID", collectionParameter);
        }
    
        public virtual ObjectResult<MstCollection> GET_COLLECTION_ID(string collection, MergeOption mergeOption)
        {
            var collectionParameter = collection != null ?
                new ObjectParameter("Collection", collection) :
                new ObjectParameter("Collection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCollection>("GET_COLLECTION_ID", mergeOption, collectionParameter);
        }
    
        public virtual ObjectResult<MstFWRDesign> GET_DESIGN_ID(string design)
        {
            var designParameter = design != null ?
                new ObjectParameter("Design", design) :
                new ObjectParameter("Design", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFWRDesign>("GET_DESIGN_ID", designParameter);
        }
    
        public virtual ObjectResult<MstFWRDesign> GET_DESIGN_ID(string design, MergeOption mergeOption)
        {
            var designParameter = design != null ?
                new ObjectParameter("Design", design) :
                new ObjectParameter("Design", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFWRDesign>("GET_DESIGN_ID", mergeOption, designParameter);
        }
    
        public virtual ObjectResult<MstQuality> GET_QUALITY_ID(string quality)
        {
            var qualityParameter = quality != null ?
                new ObjectParameter("Quality", quality) :
                new ObjectParameter("Quality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstQuality>("GET_QUALITY_ID", qualityParameter);
        }
    
        public virtual ObjectResult<MstQuality> GET_QUALITY_ID(string quality, MergeOption mergeOption)
        {
            var qualityParameter = quality != null ?
                new ObjectParameter("Quality", quality) :
                new ObjectParameter("Quality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstQuality>("GET_QUALITY_ID", mergeOption, qualityParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [DbFunction("WebAPIdbEntities", "SplitStringAsTable")]
        public virtual IQueryable<string> SplitStringAsTable(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("inputString", inputString) :
                new ObjectParameter("inputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[WebAPIdbEntities].[SplitStringAsTable](@inputString, @delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<MstCategory> UploadCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCategory>("UploadCategory");
        }
    
        public virtual ObjectResult<MstCategory> UploadCategory(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstCategory>("UploadCategory", mergeOption);
        }
    
        public virtual ObjectResult<MstFWRShade> UploadFWRShade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFWRShade>("UploadFWRShade");
        }
    
        public virtual ObjectResult<MstFWRShade> UploadFWRShade(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFWRShade>("UploadFWRShade", mergeOption);
        }
    
        public virtual int UploadFWRDesign()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UploadFWRDesign");
        }
    
        public virtual int UploadFWRQualityFlatRate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UploadFWRQualityFlatRate");
        }
    
        public virtual ObjectResult<MstMatThickness> GET_MAT_THICKNESS_ID(string matThicknessValue)
        {
            var matThicknessValueParameter = matThicknessValue != null ?
                new ObjectParameter("MatThicknessValue", matThicknessValue) :
                new ObjectParameter("MatThicknessValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstMatThickness>("GET_MAT_THICKNESS_ID", matThicknessValueParameter);
        }
    
        public virtual ObjectResult<MstMatThickness> GET_MAT_THICKNESS_ID(string matThicknessValue, MergeOption mergeOption)
        {
            var matThicknessValueParameter = matThicknessValue != null ?
                new ObjectParameter("MatThicknessValue", matThicknessValue) :
                new ObjectParameter("MatThicknessValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstMatThickness>("GET_MAT_THICKNESS_ID", mergeOption, matThicknessValueParameter);
        }
    
        public virtual ObjectResult<MstHsn> GET_HSN_ID(string hsnValue)
        {
            var hsnValueParameter = hsnValue != null ?
                new ObjectParameter("HsnValue", hsnValue) :
                new ObjectParameter("HsnValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstHsn>("GET_HSN_ID", hsnValueParameter);
        }
    
        public virtual ObjectResult<MstHsn> GET_HSN_ID(string hsnValue, MergeOption mergeOption)
        {
            var hsnValueParameter = hsnValue != null ?
                new ObjectParameter("HsnValue", hsnValue) :
                new ObjectParameter("HsnValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstHsn>("GET_HSN_ID", mergeOption, hsnValueParameter);
        }
    
        public virtual ObjectResult<MstUnitOfMeasure> GET_UOM_ID(string uOMValue)
        {
            var uOMValueParameter = uOMValue != null ?
                new ObjectParameter("UOMValue", uOMValue) :
                new ObjectParameter("UOMValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstUnitOfMeasure>("GET_UOM_ID", uOMValueParameter);
        }
    
        public virtual ObjectResult<MstUnitOfMeasure> GET_UOM_ID(string uOMValue, MergeOption mergeOption)
        {
            var uOMValueParameter = uOMValue != null ?
                new ObjectParameter("UOMValue", uOMValue) :
                new ObjectParameter("UOMValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstUnitOfMeasure>("GET_UOM_ID", mergeOption, uOMValueParameter);
        }
    
        public virtual ObjectResult<MstSupplier> GET_SUPPLIER_ID(string supplierValue)
        {
            var supplierValueParameter = supplierValue != null ?
                new ObjectParameter("SupplierValue", supplierValue) :
                new ObjectParameter("SupplierValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstSupplier>("GET_SUPPLIER_ID", supplierValueParameter);
        }
    
        public virtual ObjectResult<MstSupplier> GET_SUPPLIER_ID(string supplierValue, MergeOption mergeOption)
        {
            var supplierValueParameter = supplierValue != null ?
                new ObjectParameter("SupplierValue", supplierValue) :
                new ObjectParameter("SupplierValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstSupplier>("GET_SUPPLIER_ID", mergeOption, supplierValueParameter);
        }
    
        public virtual ObjectResult<MstFomDensity> GET_DENSITY_ID(string density)
        {
            var densityParameter = density != null ?
                new ObjectParameter("Density", density) :
                new ObjectParameter("Density", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFomDensity>("GET_DENSITY_ID", densityParameter);
        }
    
        public virtual ObjectResult<MstFomDensity> GET_DENSITY_ID(string density, MergeOption mergeOption)
        {
            var densityParameter = density != null ?
                new ObjectParameter("Density", density) :
                new ObjectParameter("Density", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFomDensity>("GET_DENSITY_ID", mergeOption, densityParameter);
        }
    
        public virtual ObjectResult<MstPattern> GET_PATTERN_ID(string pattern)
        {
            var patternParameter = pattern != null ?
                new ObjectParameter("Pattern", pattern) :
                new ObjectParameter("Pattern", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstPattern>("GET_PATTERN_ID", patternParameter);
        }
    
        public virtual ObjectResult<MstPattern> GET_PATTERN_ID(string pattern, MergeOption mergeOption)
        {
            var patternParameter = pattern != null ?
                new ObjectParameter("Pattern", pattern) :
                new ObjectParameter("Pattern", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstPattern>("GET_PATTERN_ID", mergeOption, patternParameter);
        }
    
        public virtual ObjectResult<MstFomSuggestedMM> GET_SUGGESTED_MM_ID(string suggestedMMValue)
        {
            var suggestedMMValueParameter = suggestedMMValue != null ?
                new ObjectParameter("SuggestedMMValue", suggestedMMValue) :
                new ObjectParameter("SuggestedMMValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFomSuggestedMM>("GET_SUGGESTED_MM_ID", suggestedMMValueParameter);
        }
    
        public virtual ObjectResult<MstFomSuggestedMM> GET_SUGGESTED_MM_ID(string suggestedMMValue, MergeOption mergeOption)
        {
            var suggestedMMValueParameter = suggestedMMValue != null ?
                new ObjectParameter("SuggestedMMValue", suggestedMMValue) :
                new ObjectParameter("SuggestedMMValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstFomSuggestedMM>("GET_SUGGESTED_MM_ID", mergeOption, suggestedMMValueParameter);
        }
    
        public virtual ObjectResult<MstTailor> GET_TAILOR_ID(string tailor)
        {
            var tailorParameter = tailor != null ?
                new ObjectParameter("Tailor", tailor) :
                new ObjectParameter("Tailor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstTailor>("GET_TAILOR_ID", tailorParameter);
        }
    
        public virtual ObjectResult<MstTailor> GET_TAILOR_ID(string tailor, MergeOption mergeOption)
        {
            var tailorParameter = tailor != null ?
                new ObjectParameter("Tailor", tailor) :
                new ObjectParameter("Tailor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MstTailor>("GET_TAILOR_ID", mergeOption, tailorParameter);
        }
    }
}
