

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IMSWebApi.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WebAPIdbEntities : DbContext
{
    public WebAPIdbEntities()
        : base("name=WebAPIdbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CFGRoleMenu> CFGRoleMenus { get; set; }

    public virtual DbSet<MstMenu> MstMenus { get; set; }

    public virtual DbSet<MstRole> MstRoles { get; set; }

    public virtual DbSet<MstUser> MstUsers { get; set; }

    public virtual DbSet<MstuserType> MstuserTypes { get; set; }

}

}

